### ISSUE TITLE
Feature requests, bugs and ideas

### ISSUE THREAD

**Issue by orlov0562** [mitchelldmiller/quick-mail-wp-plugin#7]
Hi Mitchell,

Thank you for great plugin and rapid reaction for feature request!

I have found bug, few problems and have some new ideas, so I decide to put everything here into one ticket. May be you can find some ideas useful for you.

I also have web dev experience, so I try to write more details from this side.

**BUGS:**

- Message in commenters dropdown should be cutted with mb_* functions to avoid problems with multibyte strings (I mean $str=mb_substr($str,0,100,'utf-8'))
![image](https://user-images.githubusercontent.com/1763904/27760073-4b761086-5e47-11e7-90e0-579ed11e69ad.png)
(The string for test is: Запись в посольство Словакии на собеседование)

**PROBLEMS:**

- If user has not filled Name/Surname, then QuickMail displays an error "Error: Incomplete User Profile".
![image](https://user-images.githubusercontent.com/1763904/27760244-524f487e-5e4b-11e7-8ab1-b2d6a68e653d.png)
May be it's some core idea, but I think you can use "Display Name" (see [wp_get_current_user](https://codex.wordpress.org/Function_Reference/wp_get_current_user) function) to get name representation that user choose into their account settings (for example I don't want leave my name/surname and want to use my username instead)
![image](https://user-images.githubusercontent.com/1763904/27760081-7107ac56-5e47-11e7-9284-0fba7e6cbd31.png)

-  When I have few last comments from same user, I see username with a post subject into "Commenters" dropdown and I should choose every item to see what comment I should choose. May be make sense to use snippet not from post subject, but from comment text, in this case I will not have problems to select right comment.
![image](https://user-images.githubusercontent.com/1763904/27760088-a034d9fe-5e47-11e7-8d3e-e10acbb5dcb1.png)

**FEATURE REQUEST:**

- Append "QuickMail" link to comments controls into "Admin/Comments" section. So we can just press the link and go to QuickMail with already selected fields.
![image](https://user-images.githubusercontent.com/1763904/27760101-ead39248-5e47-11e7-8aa6-0a1ac3f0d807.png)
(as I remember you can use [comment_row_actions](https://developer.wordpress.org/reference/hooks/comment_row_actions/) hook for this)

- Append an option (may be dropdown) for admins, to choose what email/name they want to use as letter sender: user name/email, or blog name/administrative email. It's will be useful when you want sent mail from "WebSite < support @ website.com > " instead of admin personal mail.
![image](https://user-images.githubusercontent.com/1763904/27760112-2e2a5194-5e48-11e7-911b-3eb55035072c.png)

Thank you for your work and your time! Have a nice day.

**Comment by mitchelldmiller** [comment]
Hello Vitaliy:
Thank you for your help. I added your translation to master and dev branch.

* I never used `comment_row_actions` before. Additionally, I validate reply addresses before displaying link. I inserted __Reply with Quick Mail__ after __Reply__.

* Changed comment post title display. I extended length to 120 characters on desktop.
Thank you for test string. I duplicated it, to make it longer. It splits correctly.

![screen shot 2017-07-02 at 7 46 25 pm](https://user-images.githubusercontent.com/6073590/27774853-398569ae-5f68-11e7-89ca-e96aa5148b74.png)

I added a filter to change default displays for text and HTML.

**NOT CHANGED**
>If user has not filled Name/Surname, then QuickMail displays an error "Error: Incomplete User Profile".

![image](https://user-images.githubusercontent.com/1763904/27760244-524f487e-5e4b-11e7-8ab1-b2d6a68e653d.png)

This would require an option, because it could lead to spam. I need a few days to investigate.

Best wishes,
Mitchell

**Comment by mitchelldmiller** [comment]
Hello:
I added first / last name requirement, because I thought it improved mail.

However, it made sense to replace first / last name requirement with display name.

User wants to use that value on posts. They should be abled to send mail with it.

Best wishes,
Mitchell
